const ProductArr = {
  products: [
    {
      id: 1,
      name: "shirt 1",
      category: "shirts",
      image: "../images/p1.jpg",
      price: 35,
      brand: "brand 1",
      rating: 3.5,
      numReviews: 20,
      description: "shirt 1 description",
    },
    {
      id: 2,
      name: "shirt 2",
      category: "shirts",
      image: "../images/p1.jpg",
      price: 25,
      brand: "brand 2",
      rating: 4,
      numReviews: 25,
      description: "shirt 2 description",
    },
    {
      id: 3,
      name: "shirt 3",
      category: "shirts",
      image: "../images/p1.jpg",
      price: 45,
      brand: "brand 3",
      rating: 3.5,
      numReviews: 10,
      description: "shirt 3 description",
    },
    {
      id: 4,
      name: "shirt 4",
      category: "shirts",
      image: "../images/p1.jpg",
      price: 55,
      brand: "brand 4",
      rating: 4.5,
      numReviews: 10,
      description: "shirt 4 description",
    },
    {
      id: 5,
      name: "shirt 5",
      category: "shirts",
      image: "../images/p1.jpg",
      price: 38,
      brand: "brand 5",
      rating: 5,
      numReviews: 20,
      description: "shirt 5 description",
    },
  ],
};

export default ProductArr;
